name: Build and Deploy a Node.js Docker App to EC2

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/private:gh-action-app

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Test connectivity
        run: |
          ping ec2-54-179-241-198.ap-southeast-1.compute.amazonaws.com || true
          telnet ec2-54-179-241-198.ap-southeast-1.compute.amazonaws.com 22 || true

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          protocol: tcp
          port: 22
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/private:gh-action-app
            docker stop node-app || true
            docker rm node-app || true
            docker run -d --name node-app -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/private:gh-action-app
